### ISSUE TITLE
Hello Word example doesn't compile and doesn't works.

### ISSUE THREAD

**Issue by ijiki16** [bonezegei/Bonezegei_LCD1602_I2C#1]
<img width="1367" alt="Screenshot 2024-03-17 at 22 15 36" src="https://github.com/bonezegei/Bonezegei_LCD1602_I2C/assets/37273763/aca04647-9a63-4af2-b1d5-34de6d1fafec">

Board: Arduino Uno R3
IDE: Arduino IDE version 2.3.2

 I tried to `#include <Wire.h>`  but same error.

**Comment by bonezegei** [comment]
Good Day,

I've updated the library. It might take a couple of hours for the changes to reflect on the Arduino IDE. Thanks for bringing this to my attention.

**Comment by ijiki16** [comment]
Thanks for quick response and fix, with version 1.0.3 every example code works perfectly 🙌
